In [1]:
import numpy as np

# Key

In [2]:
key = np.array([
    [3, 10, 20],
    [20, 9, 17],
    [9, 4, 17]
])

In [3]:
key.shape[0] == key.shape[1]

True

In [5]:
np.linalg.det(key) != 0

True

In [6]:
m = "attack is to night"

In [7]:
import commons
m = commons.preprocessing(m)

In [8]:
m

'attackistonight'

In [9]:
plaintext = commons.lettersOfPlaintext(m)

In [10]:
plaintext

['a', 't', 't', 'a', 'c', 'k', 'i', 's', 't', 'o', 'n', 'i', 'g', 'h', 't']

In [11]:
plaintext_idx = []
for i in plaintext:
    plaintext_idx.append(commons.letterToNumber(i))

In [12]:
plaintext_idx

[0, 19, 19, 0, 2, 10, 8, 18, 19, 14, 13, 8, 6, 7, 19]

In [13]:
plaintext_matrix = np.array(plaintext_idx)

In [14]:
plaintext_matrix

array([ 0, 19, 19,  0,  2, 10,  8, 18, 19, 14, 13,  8,  6,  7, 19])

In [15]:
plaintext_matrix.resize(5,3)

In [16]:
plaintext_matrix

array([[ 0, 19, 19],
       [ 0,  2, 10],
       [ 8, 18, 19],
       [14, 13,  8],
       [ 6,  7, 19]])

# Encryption

In [22]:
encryption = np.matmul(plaintext_matrix, key) % 26

In [23]:
encryption

array([[ 5, 13, 22],
       [ 0,  6, 22],
       [ 9,  6,  9],
       [10,  3, 13],
       [17, 17, 16]], dtype=int32)

In [24]:
encryption.resize(1, 15)

In [30]:
ciphertext = []
for i in encryption.tolist()[0]:
    ciphertext.append(commons.numberToLetter(i))

In [31]:
ciphertext

['f', 'n', 'w', 'a', 'g', 'w', 'j', 'g', 'j', 'k', 'd', 'n', 'r', 'r', 'q']

In [32]:
plaintext

['a', 't', 't', 'a', 'c', 'k', 'i', 's', 't', 'o', 'n', 'i', 'g', 'h', 't']

# Decryption

In [33]:
from sympy import Matrix

In [34]:
inv_key = Matrix(key).inv_mod(26)

In [37]:
inv_key = np.array(inv_key)

In [38]:
inv_key

array([[11, 22, 14],
       [7, 9, 21],
       [17, 0, 3]], dtype=object)

In [43]:
inv_key = inv_key.astype(float)

In [45]:
np.matmul(key, inv_key)%26

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
encryption.resize(5, 3)

In [53]:
decryption = np.matmul(encryption, inv_key) % 26

In [54]:
decryption

array([[ 0., 19., 19.],
       [ 0.,  2., 10.],
       [ 8., 18., 19.],
       [14., 13.,  8.],
       [ 6.,  7., 19.]])

In [55]:
decryption.resize(1, 15)

In [61]:
restored_text = []
for i in decryption.tolist()[0]:
    restored_text.append(commons.numberToLetter(i))

In [62]:
restored_text

['a', 't', 't', 'a', 'c', 'k', 'i', 's', 't', 'o', 'n', 'i', 'g', 'h', 't']